<?php

namespace Proxies\__CG__\ServiceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lignes extends \ServiceBundle\Entity\Lignes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idLigne', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'quantite', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idArticle', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idPanier'];
        }

        return ['__isInitialized__', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idLigne', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'quantite', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idArticle', '' . "\0" . 'ServiceBundle\\Entity\\Lignes' . "\0" . 'idPanier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lignes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLigne()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLigne();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLigne', []);

        return parent::getIdLigne();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite($quantite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', [$quantite]);

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', []);

        return parent::getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArticle(\ServiceBundle\Entity\Articles $idArticle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArticle', [$idArticle]);

        return parent::setIdArticle($idArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArticle', []);

        return parent::getIdArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPanier(\ServiceBundle\Entity\Paniers $idPanier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPanier', [$idPanier]);

        return parent::setIdPanier($idPanier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPanier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPanier', []);

        return parent::getIdPanier();
    }

}
